### ISSUE TITLE
URGENT REPONDEZ MOI

### ISSUE THREAD

**Issue by VictorADS** [JulienMrgrd/MuzikFinder#1]
Attention vous faites des delegations de doGet en doPost, ce qui est TRES DANGEREUX A FAIRE NE EFFET
RD NOUS A STIPULE QUE LUTILISATION DES METHOD DEVAIT CORRESPONDRE A LEUR TRAITEMENT.
AKA 

GET : Recuperer une donnée
POST : crée une donnée
PUT : mettre à jour une donnée
DELETE : supprimer une donnée

Bien à vous cordialement
Qu'on se le dise

**Comment by JulienMrgrd** [comment]
This ticket has been closed as the guidelines are not followed.
